Subject: Re: Questions about the License
From: Mark Wales <support@turgs.com>
To: Phillip Han <passcom.net@gmail.com>
Date: Wed, 08 Apr 2020 12:57:27 +0900

Hi Phillip,

Both Email Address and Activation Key are Case Sensitive, Make sure you are not leaving any extra space before entering the email id and activation key

If you are still facing the same issue we are sending you the Manual Activation method for product activation. Please find the attached file EMLConverter.r. Kindly follow the below steps to activate the product:

Please ensure that the specific product is not active in your system at the time of activation.

1) Download the file EMLConverter.r
2) Rename the file to EMLConverter.reg (change .r to .reg)
3) Double click on the .reg file and click on yes button.
4) Run the software

Please get back to us if you need further assistance.

Thanks & Regards,
Alisa

On Wed, Apr 8, 2020 at 5:28 AM Phillip Han <passcom.net@gmail.com<mailto:passcom.net@gmail.com>> wrote:
Thank you for your reply.

I bought Standard License as your recommendation.

Today morning, I downloaded install file as described in email I received after purchased, and move it to the computer which is offlined but the Activation is not working.

Please find attached photo and send back further instruction.

Thank you.


2020년 4월 7일 (화) 오후 1:06, Mark Wales <support@turgs.com<mailto:support@turgs.com>>님이 작성:
Hi Phillip,

Thank you for contacting us!

We would suggest you to use our software BitRecover EML Converter Wizard to convert your EML files into PST format.
Software Reference: https://www.bitrecover.com/eml-converter/  Demo version will convert your 25 EML files per folder.
Demonstration Video: https://www.youtube.com/watch?v=kx4Wfg5usk0&t=53&authuser=1

NOTE: After the successful conversion kindly open the converted PST file in outlook using File>> Open & Export>> Open Outlook data file>> Select converted PST file from the desktop.

Yes, you can purchase the Standard License of the software program or activate the same license on upto 2 machines with the same activation details, it will cost you $29.
Purchase URL:  https://order.shareit.com/cart/add?vendorid=200270618&PRODUCT[300883194]=1

Next, I wonder if it is possible to install in an offline environment. Some software can only be installed in the online environment when you enter the authentication key, but can your product be installed in the offline environment?
Yes, you do not need internet connectivity to save EML files to another file format. You need to simply install the software on the machine, activate it with the license details and perform the offline conversion.

Hope it helps, please get back to us if you need any further assistance.

Thanks & Regards,
Alisa

On Tue, Apr 7, 2020 at 4:39 AM Phillip Han <passcom.net@gmail.com<mailto:passcom.net@gmail.com>> wrote:
Hello.

I am writing to you because I have a question before purchasing your product.
The product I want to buy is EML to PST Convertor.

First, I am going to use it on my company computer, so I wonder if it is okay to purchase Standard License. I know that we're going to install it on two or fewer computers, and most software licenses are classified for commercial and non-commercial purposes, but can we purchase Standard License if we install it on only one computer?

Next, I wonder if it is possible to install in an offline environment. Some software can only be installed in the online environment when you enter the authentication key, but can your product be installed in the offline environment?

Please reply.

B.RGDS
